#!/bin/bash
#
aeg=$(date +%H)

if [[ $aeg -ge 6 ]] && [[ $aeg -le 11 ]]
then
	echo "Tere hommikust, $USER!"
elif [[ $aeg -ge 12 ]] && [[ $aeg -le 17 ]]
then
	echo "Tere päevast, $USER!"
elif [[ $aeg -ge 18 ]] && [[ $aeg -le 21 ]]
then
	echo "Tere õhtust, $USER!"
elif [[ $aeg -ge 22 ]] && [[ $aeg -le 24 ]]
then
	echo "Head ööd, $USER!"
else
	echo "Vigane sisend"
fi
#
