#!/bin/bash
#
echo "A kylg" # kysib sult A kylje v22rtust
read A
echo "B kylg" # kysib sult B kylje v22rtust
read B
BSquared=$(($B**2)) # arvutab B ruudu
ASquared=$(($A**2)) # arvutab A ruudu
CSquared=$(($BSquared+$ASquared)) # arvutab hypoteenuse
Hypot=$(echo "scale=2;sqrt($CSquared)"|bc) # valjastab hypoteenuse t2isarvulised v22rtused
echo "A = $A" # v2ljastab A v22rtuse
echo "B = $B" # v2ljastab B v22rtuse
echo "C = $Hypot" # v2ljastab C v22rtuse
#
#
