#!/bin/bash
echo "reisijate arv grupis"
read reisijad 
echo "kohtade arv bussis"
read kohad
kohtade_arv=`expr $kohad / $reisijad`
inimesed=`expr $kohad - $reisijad`
bussid=`expr $reisijad / $kohad`
ylejaanud=`expr $reisijad % $kohad`
echo "Kokku on vaja $bussid taisbussi ja ning ylejaab $ylejaanud"
#
#skripti lõpp
